// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qMRI.Infrastructure.Persistence;

#nullable disable

namespace qMRI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(qMRIDbContext))]
    [Migration("20260715080432_AddQuestionIntensity")]
    partial class AddQuestionIntensity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.AdminRecord", b =>
                {
                    b.Property<Guid>("AdminRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedByFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedByUserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("AssignedDepartments")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AssignedQuestionIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedToFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedToUserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("AdminRecordId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("AssignedAtUtc");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("Admin_record", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Assessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departments")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ScoredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ScoringModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedQuestionIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ScoringModelId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Assessments", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.AssessmentResponse", b =>
                {
                    b.Property<Guid>("AssessmentResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<DateTime>("AnsweredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Findings")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("Points")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssessmentResponseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AssessmentId", "QuestionId")
                        .IsUnique();

                    b.ToTable("AssessmentResponses", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.AssessmentScore", b =>
                {
                    b.Property<Guid>("AssessmentScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnsweredCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaturityLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("SubModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssessmentScoreId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubModuleId");

                    b.HasIndex("AssessmentId", "Scope");

                    b.ToTable("AssessmentScores", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.MaturityBand", b =>
                {
                    b.Property<Guid>("MaturityBandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TmmiLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaturityBandId");

                    b.HasIndex("ScoringModelId", "SortOrder");

                    b.ToTable("MaturityBands", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ModuleId");

                    b.HasIndex("CategoryId", "Code")
                        .IsUnique();

                    b.ToTable("Modules", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpectedAnswer")
                        .HasColumnType("int");

                    b.Property<string>("Guidance")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");
                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("SubModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("QuestionId");

                    b.HasIndex("SubModuleId");

                    b.ToTable("Questions", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RecommendationId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Recommendations", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.ScoringModel", b =>
                {
                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ScoringModelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScoringModels", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.ScoringRule", b =>
                {
                    b.Property<Guid>("ScoringRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<decimal>("Points")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScoringRuleId");

                    b.HasIndex("ScoringModelId", "Answer")
                        .IsUnique();

                    b.ToTable("ScoringRules", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.SubModule", b =>
                {
                    b.Property<Guid>("SubModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SubModuleId");

                    b.HasIndex("ModuleId", "Code")
                        .IsUnique();

                    b.ToTable("SubModules", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RecordDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("UserRecordId");

                    b.HasIndex("AssessmentId")
                        .IsUnique();

                    b.HasIndex("RecordDateUtc");

                    b.HasIndex("UserId");

                    b.ToTable("user_record", "asmt");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.HealthCheck", b =>
                {
                    b.Property<int>("HealthCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthCheckId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("HealthCheckId");

                    b.ToTable("HealthCheck", (string)null);
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "sec");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", "sec");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Fresher");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("IdentityAccessExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("RequestedRoleCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("USER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "sec");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "sec");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.AdminRecord", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Common.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Common.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Assessment", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.ScoringModel", "ScoringModel")
                        .WithMany()
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("qMRI.Domain.Common.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScoringModel");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.AssessmentResponse", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Assessment", "Assessment")
                        .WithMany("Responses")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Assessments.Entities.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.AssessmentScore", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Assessment", "Assessment")
                        .WithMany("Scores")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Assessments.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("qMRI.Domain.Assessments.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("qMRI.Domain.Assessments.Entities.SubModule", "SubModule")
                        .WithMany()
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assessment");

                    b.Navigation("Category");

                    b.Navigation("Module");

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.MaturityBand", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.ScoringModel", "ScoringModel")
                        .WithMany("MaturityBands")
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringModel");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Module", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Category", "Category")
                        .WithMany("Modules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Question", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.SubModule", "SubModule")
                        .WithMany("Questions")
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Recommendation", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Assessment", "Assessment")
                        .WithMany("Recommendations")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Assessments.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("qMRI.Domain.Assessments.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assessment");

                    b.Navigation("Category");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.ScoringRule", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.ScoringModel", "ScoringModel")
                        .WithMany("Rules")
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringModel");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.SubModule", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Module", "Module")
                        .WithMany("SubModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.UserRecord", b =>
                {
                    b.HasOne("qMRI.Domain.Assessments.Entities.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Common.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.RefreshToken", b =>
                {
                    b.HasOne("qMRI.Domain.Common.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.UserRole", b =>
                {
                    b.HasOne("qMRI.Domain.Common.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qMRI.Domain.Common.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Assessment", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("Responses");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Category", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Module", b =>
                {
                    b.Navigation("SubModules");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.Question", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.ScoringModel", b =>
                {
                    b.Navigation("MaturityBands");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("qMRI.Domain.Assessments.Entities.SubModule", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("qMRI.Domain.Common.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}

